const CONSTANTS = {
  ERRORS: {
    REGISTRATION_FAILED: 'REGISTRATION_FAILED',
    SEND_EMAIL_FAILED: 'SEND_EMAIL_FAILED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_EMAIL: 'INVALID_EMAIL',
    FORBIDDEN: 'FORBIDDEN',
    EMAIL_PASSWORD_REQUIRED: 'EMAIL_PASSWORD_REQUIRED',
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',
    USER_VERIFIED: 'USER_VERIFIED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
}

module.exports = { ...CONSTANTS }
